name       : kubectl
version    : 1.11.0
release    : 1
source     :
    - https://github.com/kubernetes/kubernetes/archive/v1.11.0.tar.gz : b264dec72bb383fe6fc9063a1e270c00e734005e7af578bd0b33091fd8451349
license    : Apache-2.0
component  : network.clients
summary    : Command line interface for running commands against Kubernetes clusters
description: |
    kubectl is a command line interface for running commands against Kubernetes clusters
builddeps  :
    - golang
    - rsync
build      : |
    hack/generate-docs.sh
    %make kubectl
install    : |
    install -dm00644 $installdir/usr/share/man/man1
    cp docs/man/man1/kubectl*.1 $installdir/usr/share/man/man1
    install -Dm00755 _output/bin/kubectl $installdir/usr/bin/kubectl
