name       : kubectl
version    : 1.21.2
release    : 31
source     :
    - https://github.com/kubernetes/kubernetes/archive/v1.21.2.tar.gz : 1173f1ea1b6d291666715f54c7d6dd9c54357c0f80aa453f243fd7b3a7498972
license    : Apache-2.0
component  : network.clients
summary    : Command line interface for running commands against Kubernetes clusters
description: |
    kubectl is a command line interface for running commands against Kubernetes clusters
builddeps  :
    - golang
    - rsync
build      : |
    hack/update-generated-docs.sh
    %make kubectl
install    : |
    install -dm00644 $installdir/usr/share/man/man1
    cp docs/man/man1/kubectl*.1 $installdir/usr/share/man/man1
    install -Dm00755 _output/bin/kubectl $installdir/usr/bin/kubectl
    # Install completion scripts
    _output/bin/kubectl completion bash > kubectl-bash-completion
    _output/bin/kubectl completion zsh > kubectl-zsh-completion
    install -Dm00644 kubectl-bash-completion $installdir/usr/share/bash-completion/completions/kubectl
    install -Dm00644 kubectl-zsh-completion $installdir/usr/share/zsh/site-functions/_kubectl
