name       : kubectl
version    : 1.17.0
release    : 13
source     :
    - https://github.com/kubernetes/kubernetes/archive/v1.17.0.tar.gz : b4f82f5006ff945edc17726ac93489173876313855020e7760b1c189fb402bb1
license    : Apache-2.0
component  : network.clients
summary    : Command line interface for running commands against Kubernetes clusters
description: |
    kubectl is a command line interface for running commands against Kubernetes clusters
builddeps  :
    - golang
    - rsync
build      : |
    hack/update-generated-docs.sh
    %make kubectl
install    : |
    install -dm00644 $installdir/usr/share/man/man1
    cp docs/man/man1/kubectl*.1 $installdir/usr/share/man/man1
    install -Dm00755 _output/bin/kubectl $installdir/usr/bin/kubectl
    # Install completion scripts
    _output/bin/kubectl completion bash > kubectl-bash-completion
    _output/bin/kubectl completion zsh > kubectl-zsh-completion
    install -Dm00644 kubectl-bash-completion $installdir/usr/share/bash-completion/completions/kubectl
    install -Dm00644 kubectl-zsh-completion $installdir/usr/share/zsh/site-functions/_kubectl
